name: Deploy

# only trigger on tags, `verify` has already been triggered by push to PR
on:
  push:
    tags: ["fasten-maven-plugin-[0-9]+.[0-9]+.[0-9]+"]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of distributionManagement/repository/id
          settings-path: ${{ github.workspace }} # location of settings.xml

      - name: Deploy Maven packages
        run: mvn -B -ntp clean deploy -s ${{ github.workspace }}/settings.xml
        env:
          # auth necessary to access GitHub Maven registries
          GITHUB_TOKEN: ${{ github.token }}